---
versions:
  - ""
  - "-auto-dev"
  - "-auto"
  - "-dev"
slims:
  - aopo
  - bao
  - bfo
  - bto
  - ccont
  - cheminf
  - chebi
  - chmo
  - clo
  - efo
  - envo
  - fabio
  - go
  - iao
  - ncit
  - npo
  - oae
  - obcs
  - obi
  - pato
  - sio
  - uberon
  - uo
props:
  - bao
  - cheminf
  - npo
  - sio
  - ro
  - cito
robot:
  robot-jar: https://github.com/ontodev/robot/releases/download/v1.9.4/robot.jar
  robot-wrapper: https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
slimmer: https://github.com/enanomapper/slimmer/releases/download/v1.0.2/slimmer-1.0.2-jar-with-dependencies.jar


  
